
plugins:
  plugin_name:
    tables:
      table_name:
        unique_columns: [id, ]
        show_first: [id, ]
        hide_columns: [id, ]

  docker:
    table:
      unique_columns: [id, ]
      show_first: [id, ]
      hide_columns: [id, ]

  kubernetes:
    table:
      unique_columns: [uid, ]
      show_first: [uid, ]
      hide_columns: [uid, ]
                
  hackernews:
    table:
      unique_columns: [id, ]
      show_first: [id, ]
      hide_columns: [id, ]